### ISSUE TITLE
Error in TooltipSystem if not setting a valid path

### ISSUE THREAD

**Issue by 89pleasure** [yenyang/Anarchy#5]
Howdy, 

I had an issue with Anarchy and ExtendedTooltip together. I figured it's necessary to add a unique path to the Tooltip object. Otherwise it will throw an error. I just wanted to let you know since Anarchy currently is not adding a path to it's mouse tooltip. Which would lead to errors if other mods is also not adding an unique path. 

It seems if not adding one will create a path with value "0". So it could happen to conflict if another mod does have that too.

I just simply do:

```c#
m_NetToolMode = new StringTooltip()
{
    path = "etNetToolMode",
};
```

**Comment by yenyang** [comment]
I think the problem in this case is that the path is to an old coui location, that I forgot to update. I’m going to patch it soon with the right path. If there are still issues after I fix it let me know.

**Comment by 89pleasure** [comment]
Do you mean the issue with the icon throwing a 404 error? 
If you mean that, that's another one. Is related to tooltips too.

**Comment by yenyang** [comment]
In that case I’ll add the paths as suggested. Thanks.

**Comment by yenyang** [comment]
Paths have been added and the icon coui path has been updated with Patch for version 1.4.3. I'm going to close this, but you can open it back up if there is still an issue between this and Extended tooltip. Thanks for pointing out the issue.
